version: '3.9'

services:
  nginx:
    image: ${REGISTRY_ADDRESS}/nginx:${IMAGE_TAG}
    restart: always
    depends_on:
      - php-fpm
    ports:
      - "80:80"

  php-fpm:
    image: ${REGISTRY_ADDRESS}/php-fpm:${IMAGE_TAG}
    restart: always
    environment:
      APP_SECRET: ${DASHBOARD_APP_SECRET}
      DATABASE_URL: postgresql://dashboard:${DASHBOARD_DB_PASSWORD}@postgres:5432/dashboard?serverVersion=13&charset=utf8
      REDIS_URL: tcp://redis:6379?password=${DASHBOARD_REDIS_PASSWORD}
      MAILER_DSN: smtp://localhost
      OAUTH_GITHUB_SECRET: ${DASHBOARD_OAUTH_GITHUB_SECRET}
    depends_on:
      - postgres
      - redis

  php-cli:
    image: ${REGISTRY_ADDRESS}/php-cli:${IMAGE_TAG}
    restart: always
    environment:
      APP_SECRET: ${DASHBOARD_APP_SECRET}
      DATABASE_URL: postgresql://dashboard:${DASHBOARD_DB_PASSWORD}@postgres:5432/dashboard?serverVersion=13&charset=utf8
      REDIS_URL: tcp://redis:6379?password=${DASHBOARD_REDIS_PASSWORD}
      MAILER_DSN: smtp://localhost
      OAUTH_GITHUB_SECRET: ${DASHBOARD_OAUTH_GITHUB_SECRET}
    depends_on:
      - postgres
      - redis

  postgres:
    image: ${REGISTRY_ADDRESS}/postgres:${IMAGE_TAG}
    restart: always
    volumes:
      - dashboard-postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: dashboard
      POSTGRES_PASSWORD: ${DASHBOARD_DB_PASSWORD}
      POSTGRES_DB: dashboard

  redis:
    image: ${REGISTRY_ADDRESS}/redis:${IMAGE_TAG}
    restart: always
    volumes:
      - dashboard-redis:/data
    command: redis-server --requirepass ${DASHBOARD_REDIS_PASSWORD}

volumes:
  dashboard-postgres:
  dashboard-redis:
