version: '3.9'

services:
  nginx:
    image: ${REGISTRY_ADDRESS}/nginx:${IMAGE_TAG}
    restart: always
    depends_on:
      - php-fpm
    ports:
      - "80:80"

  php-fpm:
    image: ${REGISTRY_ADDRESS}/php-fpm:${IMAGE_TAG}
    restart: always
    environment:
      APP_SECRET: ${DASHBOARD_APP_SECRET}
      DATABASE_URL: postgresql://dashboard:${DASHBOARD_DB_PASSWORD}@postgres:5432/dashboard?serverVersion=13&charset=utf8
      REDIS_URL: tcp://redis:6379?password=${DASHBOARD_REDIS_PASSWORD}
      MAILER_DSN: ${DASHBOARD_MAILER_DSN}
      OAUTH_GITHUB_SECRET: ${DASHBOARD_OAUTH_GITHUB_SECRET}
      STORAGE_BASE_URL: ${STORAGE_BASE_URL}
      STORAGE_FTP_HOST: ${STORAGE_FTP_HOST}
      STORAGE_FTP_USERNAME: ${STORAGE_FTP_USERNAME}
      STORAGE_FTP_PASSWORD: ${STORAGE_FTP_PASSWORD}
      MESSENGER_TRANSPORT_DSN: redis://queue-redis:6379/messages
      CENTRIFUGO_WS_HOST: ${CENTRIFUGO_WS_HOST}
      CENTRIFUGO_API_HOST: http://centrifugo:8000
      CENTRIFUGO_API_KEY: ${CENTRIFUGO_API_KEY}
      CENTRIFUGO_SECRET: ${CENTRIFUGO_SECRET}
      OAUTH_ENCRYPTION_KEY: ${OAUTH_ENCRYPTION_KEY}
    depends_on:
      - postgres
      - redis
      - queue-redis
      - centrifugo

  php-cli:
    image: ${REGISTRY_ADDRESS}/php-cli:${IMAGE_TAG}
    restart: always
    environment:
      APP_SECRET: ${DASHBOARD_APP_SECRET}
      DATABASE_URL: postgresql://dashboard:${DASHBOARD_DB_PASSWORD}@postgres:5432/dashboard?serverVersion=13&charset=utf8
      REDIS_URL: tcp://redis:6379?password=${DASHBOARD_REDIS_PASSWORD}
      MAILER_DSN: ${DASHBOARD_MAILER_DSN}
      OAUTH_GITHUB_SECRET: ${DASHBOARD_OAUTH_GITHUB_SECRET}
      STORAGE_BASE_URL: ${STORAGE_BASE_URL}
      STORAGE_FTP_HOST: ${STORAGE_FTP_HOST}
      STORAGE_FTP_USERNAME: ${STORAGE_FTP_USERNAME}
      STORAGE_FTP_PASSWORD: ${STORAGE_FTP_PASSWORD}
      MESSENGER_TRANSPORT_DSN: redis://queue-redis:6379/messages
      CENTRIFUGO_WS_HOST: ${CENTRIFUGO_WS_HOST}
      CENTRIFUGO_API_HOST: http://centrifugo:8000
      CENTRIFUGO_API_KEY: ${CENTRIFUGO_API_KEY}
      CENTRIFUGO_SECRET: ${CENTRIFUGO_SECRET}
      OAUTH_ENCRYPTION_KEY: ${OAUTH_ENCRYPTION_KEY}
    depends_on:
      - postgres
      - redis
      - queue-redis
      - centrifugo

  queue-worker:
    image: ${REGISTRY_ADDRESS}/php-cli:${IMAGE_TAG}
    restart: always
    environment:
      APP_SECRET: ${DASHBOARD_APP_SECRET}
      DATABASE_URL: postgresql://dashboard:${DASHBOARD_DB_PASSWORD}@postgres:5432/dashboard?serverVersion=13&charset=utf8
      REDIS_URL: tcp://redis:6379?password=${DASHBOARD_REDIS_PASSWORD}
      MAILER_DSN: ${DASHBOARD_MAILER_DSN}
      OAUTH_GITHUB_SECRET: ${DASHBOARD_OAUTH_GITHUB_SECRET}
      STORAGE_BASE_URL: ${STORAGE_BASE_URL}
      STORAGE_FTP_HOST: ${STORAGE_FTP_HOST}
      STORAGE_FTP_USERNAME: ${STORAGE_FTP_USERNAME}
      STORAGE_FTP_PASSWORD: ${STORAGE_FTP_PASSWORD}
      MESSENGER_TRANSPORT_DSN: redis://queue-redis:6379/messages
      CENTRIFUGO_WS_HOST: ${CENTRIFUGO_WS_HOST}
      CENTRIFUGO_API_HOST: http://centrifugo:8000
      CENTRIFUGO_API_KEY: ${CENTRIFUGO_API_KEY}
      CENTRIFUGO_SECRET: ${CENTRIFUGO_SECRET}
      OAUTH_ENCRYPTION_KEY: ${OAUTH_ENCRYPTION_KEY}
    depends_on:
      - postgres
      - redis
      - queue-redis
      - centrifugo
    command: sh -c "sleep 30 && php bin/console messenger:consume async -vv"

  postgres:
    image: ${REGISTRY_ADDRESS}/postgres:${IMAGE_TAG}
    restart: always
    volumes:
      - dashboard-postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: dashboard
      POSTGRES_PASSWORD: ${DASHBOARD_DB_PASSWORD}
      POSTGRES_DB: dashboard

  redis:
    image: ${REGISTRY_ADDRESS}/redis:${IMAGE_TAG}
    restart: always
    volumes:
      - dashboard-redis:/data
    command: redis-server --requirepass ${DASHBOARD_REDIS_PASSWORD}

  queue-redis:
    image: ${REGISTRY_ADDRESS}/redis:${IMAGE_TAG}
    restart: always
    volumes:
      - dashboard-queue-redis:/data

  centrifugo:
    image: ${REGISTRY_ADDRESS}/centrifugo:${IMAGE_TAG}
    restart: always
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
    environment:
      CENTRIFUGO_ALLOWED_ORIGINS: ${CENTRIFUGO_ALLOWED_ORIGINS}
      CENTRIFUGO_TOKEN_HMAC_SECRET_KEY: ${CENTRIFUGO_SECRET}
      CENTRIFUGO_API_KEY: ${CENTRIFUGO_API_KEY}
    ports:
      - "8000:8000"

volumes:
  dashboard-postgres:
  dashboard-redis:
  dashboard-queue-redis:
