version: '3.9'

services:
  nginx:
    build:
      context: ./dashboard/docker/development
      dockerfile: nginx/nginx.docker
    volumes:
      - ./dashboard:/app:ro
    depends_on:
      - php-fpm
    ports:
      - "8080:80"

  php-fpm:
    build:
      context: ./dashboard/docker/development
      dockerfile: php/php-fpm.docker
      args:
        - USER_ID
        - GROUP_ID
    volumes:
      - ./dashboard:/app
    depends_on:
      - postgres
      - mailer

  php-cli:
    build:
      context: ./dashboard/docker/development
      dockerfile: php/php-cli.docker
      args:
        - USER_ID
        - GROUP_ID
    volumes:
      - ./dashboard:/app
    depends_on:
      - postgres
      - mailer

  postgres:
    image: postgres:13.3-alpine
    volumes:
      - dashboard-postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "54321:5432"

  node:
    image: node:lts-alpine3.14
    user: ${USER_ID}:${GROUP_ID}
    volumes:
      - ./dashboard:/app
    working_dir: /app

  mailer:
    image: mailhog/mailhog:v1.0.1
    ports:
      - "8081:8025"

volumes:
  dashboard-postgres:
